'use strict';
const $=s=>document.querySelector(s), clean=v=>String(v??'').replace(/[\u00a0\r\n]+/g,' ').replace(/\s+/g,' ').trim(), low=v=>clean(v).toLocaleLowerCase('pt-BR'), yes=v=>low(v)==='sim', esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={rows:[],filtered:[],headers:[],filters:[],charts:{},meta:null,selected:null};let C={};
const DB='URE_SBC_Educacao_Especial',STORE='dashboard',KEY='current';
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function saveDB(data){const db=await openDB();return new Promise((ok,no)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(data,KEY);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
async function loadDB(){const db=await openDB();return new Promise((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function status(t,e=false){$('#status').textContent=t;$('#status').style.color=e?'#b00020':''}
function fmtDate(v){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'medium'}).format(new Date(v))}
document.addEventListener('DOMContentLoaded',()=>{$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#user').value==='educacao'&&$('#pass').value==='101010'){sessionStorage.setItem('auth','1');showApp()}else $('#loginMsg').textContent='Usuário ou senha inválidos.'};$('#logout').onclick=()=>{sessionStorage.removeItem('auth');location.reload()};const i=$('#fileInput');$('#uploadBtn').onclick=()=>{i.value='';i.click()};i.onchange=()=>i.files[0]&&readFile(i.files[0]);$('#school').onchange=()=>{students();filter()};$('#student').onchange=()=>{filter();studentDetail()};$('#year').onchange=filter;$('#search').oninput=filter;$('#extraField').onchange=extraValues;$('#addFilter').onclick=addFilter;$('#clearFilters').onclick=clearFilters;$('#close').onclick=()=>{$('#student').value='';$('#detail').classList.add('hidden');filter()};$('#pdf').onclick=()=>window.print();$('#studentCsv').onclick=()=>S.selected&&download([S.selected],'ficha_estudante.csv');$('#filteredCsv').onclick=()=>download(S.filtered,'dados_filtrados.csv');$('#schoolCsv').onclick=()=>download(S.filtered,'resumo_estudantes_por_escola.csv');$('#expandAll').onclick=()=>document.querySelectorAll('#schoolSummaries details').forEach(d=>d.open=true);$('#collapseAll').onclick=()=>document.querySelectorAll('#schoolSummaries details').forEach(d=>d.open=false);['qCase','qSupport','qAee','qTransport','qMissing'].forEach(id=>$('#'+id).onchange=filter);if(sessionStorage.getItem('auth')==='1')showApp()});
async function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');try{const d=await loadDB();if(d?.rows?.length){S.rows=d.rows;S.headers=d.headers;S.meta=d.meta;mapCols();setup();status(`Dados restaurados: ${S.rows.length} registros • ${S.meta.file}`);$('#lastUpload').textContent='Último upload: '+fmtDate(S.meta.uploadedAt)}else status('Nenhuma planilha salva neste navegador.')}catch(e){status('Não foi possível recuperar os dados salvos: '+e.message,true)}}
function readFile(file){if(typeof XLSX==='undefined')return status('Leitor XLSX não encontrado.',true);status('Lendo '+file.name+'...');const r=new FileReader();r.onload=async e=>{try{const w=XLSX.read(e.target.result,{type:'array'}),name=w.SheetNames.find(n=>/respost|sheet1/i.test(n))||w.SheetNames[0],m=XLSX.utils.sheet_to_json(w.Sheets[name],{header:1,defval:'',raw:false});let h=-1;for(let x=0;x<Math.min(30,m.length);x++)if(m[x].some(v=>low(v)==='escola')&&m[x].some(v=>low(v).includes('nome do estudante'))){h=x;break}if(h<0)throw Error('cabeçalhos Escola e Nome do estudante não encontrados.');S.headers=m[h].map(clean);S.rows=m.slice(h+1).filter(a=>a.some(v=>clean(v))).map(a=>Object.fromEntries(S.headers.map((z,j)=>[z,clean(a[j])])));mapCols();S.rows=S.rows.filter(x=>clean(x[C.school])||clean(x[C.student]));S.meta={file:file.name,sheet:name,uploadedAt:new Date().toISOString(),count:S.rows.length};await saveDB({rows:S.rows,headers:S.headers,meta:S.meta});setup();status(`SUCESSO: ${file.name} • ${S.rows.length} registros • dados salvos neste navegador`);$('#lastUpload').textContent='Último upload: '+fmtDate(S.meta.uploadedAt)}catch(x){status('ERRO: '+x.message,true)}};r.onerror=()=>status('Falha ao acessar o arquivo.',true);r.readAsArrayBuffer(file)}
function find(...t){return S.headers.find(h=>t.every(x=>low(h).includes(x)))||''}function mapCols(){C={school:find('escola'),student:find('nome','estudante'),ra:S.headers.find(h=>low(h)==='ra')||find('ra'),year:find('ano','série'),freq:find('aluno','frequente'),aee:find('frequenta','atendimento educacional'),support:find('solicitado','profissional','apoio'),caseStudy:find('aluno','estudo','caso'),transport:find('utiliza','transporte')}}
function setup(){fill('#school',unique(C.school),'Todas');fill('#year',unique(C.year),'Todos');fill('#extraField',S.headers.filter(Boolean),'Selecionar campo');students();filter()}
function unique(c,rows=S.rows){return [...new Set(rows.map(r=>clean(r[c])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true}))}function fill(s,a,l){$(s).innerHTML=`<option value="">${l}</option>`+a.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function key(r){return clean(r[C.ra])||clean(r[C.student])}function students(){const sc=$('#school').value,e=$('#student');$('#detail').classList.add('hidden');if(!sc){e.disabled=true;e.innerHTML='<option value="">Selecione primeiro a escola</option>';return}const a=S.rows.filter(r=>clean(r[C.school])===sc).map(r=>({k:key(r),n:clean(r[C.student]),ra:clean(r[C.ra])})).filter((x,i,z)=>x.k&&z.findIndex(y=>y.k===x.k)===i).sort((a,b)=>a.n.localeCompare(b.n,'pt-BR'));e.disabled=false;e.innerHTML='<option value="">Todos os estudantes</option>'+a.map(x=>`<option value="${esc(x.k)}">${esc(x.n)}${x.ra?' • RA final '+esc(x.ra.slice(-4)):''}</option>`).join('')}
function extraValues(){const f=$('#extraField').value,e=$('#extraValue');if(!f){e.disabled=true;return fill('#extraValue',[],'Todos')}fill('#extraValue',unique(f),'Todos');e.disabled=false}function addFilter(){const field=$('#extraField').value,value=$('#extraValue').value;if(field&&value&&!S.filters.some(f=>f.field===field&&f.value===value))S.filters.push({field,value});chips();filter()}function chips(){$('#chips').innerHTML=S.filters.map((f,i)=>`<span class="chip"><b>${esc(f.field)}:</b> ${esc(f.value)} <button data-i="${i}">×</button></span>`).join('');document.querySelectorAll('.chip button').forEach(b=>b.onclick=()=>{S.filters.splice(+b.dataset.i,1);chips();filter()})}
function clearFilters(){$('#school').value='';$('#year').value='';$('#search').value='';S.filters=[];['qCase','qSupport','qAee','qTransport','qMissing'].forEach(id=>$('#'+id).checked=false);chips();students();$('#detail').classList.add('hidden');filter()}
function filter(){const sc=$('#school').value,st=$('#student').value,yr=$('#year').value,q=low($('#search').value);S.filtered=S.rows.filter(r=>(!sc||clean(r[C.school])===sc)&&(!st||key(r)===st)&&(!yr||clean(r[C.year])===yr)&&S.filters.every(f=>clean(r[f.field])===f.value)&&(!$('#qCase').checked||yes(r[C.caseStudy]))&&(!$('#qSupport').checked||yes(r[C.support]))&&(!$('#qAee').checked||yes(r[C.aee]))&&(!$('#qTransport').checked||yes(r[C.transport]))&&(!$('#qMissing').checked||summaryFields().some(h=>!clean(r[h])))&&(!q||S.headers.some(h=>low(r[h]).includes(q))));render()}
function studentDetail(){const k=$('#student').value;if(!k)return $('#detail').classList.add('hidden');const a=S.rows.filter(r=>clean(r[C.school])===$('#school').value&&key(r)===k),r=a.at(-1);S.selected=r;$('#detailName').textContent=clean(r[C.student]);$('#detailSub').textContent=clean(r[C.school]);$('#detailGrid').innerHTML=S.headers.filter(Boolean).map(h=>`<div class="field ${/observa|relat|processo|profissional/i.test(h)?'wide':''}"><label>${esc(h)}</label><span class="${clean(r[h])?'':'empty'}">${clean(r[h])?esc(r[h]):'Não informado'}</span></div>`).join('');$('#detail').classList.remove('hidden');$('#detail').scrollIntoView({behavior:'smooth'})}
function render(){const r=S.filtered;$('#k1').textContent=r.length;$('#k2').textContent=new Set(r.map(x=>clean(x[C.school])).filter(Boolean)).size;$('#k3').textContent=r.filter(x=>yes(x[C.freq])).length;$('#k4').textContent=r.filter(x=>yes(x[C.aee])).length;$('#k5').textContent=r.filter(x=>yes(x[C.support])).length;$('#count').textContent=r.length+' registros';renderSummaries();$('#tbody').innerHTML=r.length?r.slice(0,200).map(x=>`<tr><td>${esc(x[C.school])}</td><td>${esc(x[C.student])}</td><td>${mask(x[C.ra])}</td><td>${esc(x[C.year])}</td><td>${pill(x[C.freq])}</td><td>${pill(x[C.aee])}</td><td>${pill(x[C.support])}</td></tr>`).join(''):'<tr><td colspan="7">Nenhum registro.</td></tr>';charts()}
function mask(v){v=clean(v);return v.length>4?'••••'+esc(v.slice(-4)):esc(v)||'—'}function pill(v){const t=clean(v)||'Não informado';return `<span class="pill ${yes(t)?'sim':low(t)==='não'?'nao':''}">${esc(t)}</span>`}function counts(c){return S.filtered.reduce((a,r)=>{const k=clean(r[c])||'Não informado';a[k]=(a[k]||0)+1;return a},{})}
function charts(){if(typeof Chart==='undefined')return;Object.values(S.charts).forEach(x=>x.destroy());let a=Object.entries(counts(C.school)).sort((x,y)=>y[1]-x[1]).slice(0,12);S.charts.s=new Chart($('#schoolChart'),{type:'bar',data:{labels:a.map(x=>x[0]),datasets:[{data:a.map(x=>x[1]),backgroundColor:'#c90027'}]},options:{maintainAspectRatio:false,indexAxis:'y',plugins:{legend:{display:false}}}});a=Object.entries(counts(C.year));S.charts.y=new Chart($('#yearChart'),{type:'doughnut',data:{labels:a.map(x=>x[0]),datasets:[{data:a.map(x=>x[1]),backgroundColor:['#c90027','#222','#6873d1','#e88b2d','#159570']}]},options:{maintainAspectRatio:false}})}
function download(rows,name){if(!rows.length)return;const q=v=>'"'+clean(v).replaceAll('"','""')+'"',csv='\ufeff'+[S.headers.map(q).join(';'),...rows.map(r=>S.headers.map(h=>q(r[h])).join(';'))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

const SUMMARY_LABELS=[
'Escola','Nome do estudante','RA','Ano/Série/Período — 2026','Data de matrícula na unidade escolar','Aluno frequente','Aluno em estudo de caso','CID','Laudo — data de expedição','Relatório de acolhimento — data','Informe a data do estudo de caso.','Informe a data do Plano de Atendimento Educacional Especializado (PAEE).','Informe a data do Plano Educacional Individualizado (PEI).','Foi solicitado profissional de apoio para o estudante?','Data da solicitação de apoio','Nome do profissional','Tipo de apoio','Existe atendimento judicial relacionado ao profissional de apoio?','Informe o número do processo SEI relacionado ao profissional de apoio.','O estudante foi indicado para Atendimento Educacional Especializado (AEE)?','O estudante frequenta o Atendimento Educacional Especializado (AEE)?','Houve declínio da família ao AEE registrado na SED?','Solicitou transporte escolar','Informe o número do processo SEI relacionado ao transporte escolar.','O estudante utiliza transporte escolar?','Informe o nome da empresa de transporte escolar.','Existe atendimento judicial relacionado ao transporte escolar?','Registre informações importantes ou observações sobre o estudante.'
];
function summaryFields(){return SUMMARY_LABELS.map(label=>label==='Escola'?C.school:label==='Nome do estudante'?C.student:label==='RA'?C.ra:label==='Ano/Série/Período — 2026'?C.year:(S.headers.find(h=>low(h)===low(label))||label))}
function renderSummaries(){
 const groups=S.filtered.reduce((a,r)=>{const k=clean(r[C.school])||'Escola não informada';(a[k]??=[]).push(r);return a},{});
 $('#summaryCount').textContent=S.filtered.length+' estudantes em '+Object.keys(groups).length+' escolas';
 $('#schoolSummaries').innerHTML=Object.keys(groups).sort((a,b)=>a.localeCompare(b,'pt-BR')).map(school=>`<details class="schoolGroup"><summary><span>${esc(school)}</span><span class="schoolBadge">${groups[school].length} estudante(s)</span></summary><div class="studentCards">${groups[school].sort((a,b)=>clean(a[C.student]).localeCompare(clean(b[C.student]),'pt-BR')).map(r=>studentCard(r)).join('')}</div></details>`).join('')||'<p>Nenhum estudante localizado com os filtros atuais.</p>';
}
function studentCard(r){const name=clean(r[C.student])||'Nome não informado',ra=clean(r[C.ra]),year=clean(r[C.year]);return `<details class="studentSummary"><summary><span>${esc(name)}</span><span>${esc(year)}${ra?' • RA final '+esc(ra.slice(-4)):''}</span></summary><div class="summaryGrid">${SUMMARY_LABELS.map((label,i)=>{const h=summaryFields()[i],v=clean(r[h]),wide=/observa|processo|profissional|empresa/i.test(label);return `<div class="summaryField ${wide?'wide':''}"><b>${esc(label)}</b><span class="${v?'':'missing'}">${v?esc(v):'Não informado'}</span></div>`}).join('')}</div></details>`}
